// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKA4FV03KSEwss98KK_nHbKB7PLzMZ_30',
    appId: '1:800777624595:web:684fa86ef8ab4b04cef3e6',
    messagingSenderId: '800777624595',
    projectId: 'agent-referral-3c9bf',
    authDomain: 'agent-referral-3c9bf.firebaseapp.com',
    storageBucket: 'agent-referral-3c9bf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVT4IBjvKxtXZSo2rgKpRg8g9RDmwMYLw',
    appId: '1:800777624595:android:4c98a74af6ea4e7ccef3e6',
    messagingSenderId: '800777624595',
    projectId: 'agent-referral-3c9bf',
    storageBucket: 'agent-referral-3c9bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi0550taAh5NL79K8Nr95rFFPHVrTAWZc',
    appId: '1:800777624595:ios:2aa143540334a0ffcef3e6',
    messagingSenderId: '800777624595',
    projectId: 'agent-referral-3c9bf',
    storageBucket: 'agent-referral-3c9bf.appspot.com',
    iosBundleId: 'com.example.agentReferral',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAi0550taAh5NL79K8Nr95rFFPHVrTAWZc',
    appId: '1:800777624595:ios:2aa143540334a0ffcef3e6',
    messagingSenderId: '800777624595',
    projectId: 'agent-referral-3c9bf',
    storageBucket: 'agent-referral-3c9bf.appspot.com',
    iosBundleId: 'com.example.agentReferral',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKA4FV03KSEwss98KK_nHbKB7PLzMZ_30',
    appId: '1:800777624595:web:453eb871fa50d7b1cef3e6',
    messagingSenderId: '800777624595',
    projectId: 'agent-referral-3c9bf',
    authDomain: 'agent-referral-3c9bf.firebaseapp.com',
    storageBucket: 'agent-referral-3c9bf.appspot.com',
  );
}
